version: "3.8"

services:
  db:
    container_name: stashify-postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
